export const SN_UTIL = 'util'
export const UTIL_SERVICE_STATUS_DESC_UPDATED = SN_UTIL + '/SERVICE_STATUS_DESC_UPDATED'
export const UITL_JOB_RECURRENCE_TIME_ZONE_UPDATED = SN_UTIL + '/JOB_RECURRENCE_TIME_ZONE_UPDATED'