export default {
    "APP_DASHBOARD_VIEW": "",
    "APP_CATALOG_VIEW": "",
    "APP_IMPORT_MONITOR_VIEW": "",
    "JOB_MANAGER_APP_VIEW": "JOB_MANAGER_APP_VIEW",
    "APP_COMMERCE_VIEW": "COMMERCEUSER_VIEW"
} as any
