name: Deploy to Firebase Hosting on release
'on':
  push:
    tags:
      - '*'
jobs:
  call-workflow-in-another-repo:
    uses: hotwax/accxui/.github/workflows/common-firebase-hosting-release.yml@main
    with:
      config-path: .github/labeler.yml
      app: hotwax/job-manager
      appDir: job-manager
      accxuiVersion: v1.0.1
    secrets:
      envPAT: ${{ secrets.envPAT }}
      HOTWAX_PUBLIC_SECRET: ${{ secrets.HOTWAX_PUBLIC_SECRET }}